version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: slack_bot_db
    environment:
      POSTGRES_USER: slackbot
      POSTGRES_PASSWORD: slackbotpass
      POSTGRES_DB: slackbot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 