"""remove base url

Revision ID: 34266abb4843
Revises: 073fede88ccd
Create Date: 2025-06-08 20:59:13.531095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34266abb4843'
down_revision = '073fede88ccd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'greyt_hr_base_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('greyt_hr_base_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ### 