"""remove is_active 2

Revision ID: 7942a015f095
Revises: d592d33b1c90
Create Date: 2025-06-09 11:20:42.364375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7942a015f095'
down_revision = 'd592d33b1c90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 