"""add_cascade_delete_to_employees

Revision ID: a82b51f857e0
Revises: fa55872b23f2
Create Date: 2025-06-15 18:07:39.794646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a82b51f857e0'
down_revision = 'fa55872b23f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 