"""remove domain

Revision ID: f2344f1a15d6
Revises: 7942a015f095
Create Date: 2025-06-13 20:19:43.724962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2344f1a15d6'
down_revision = '7942a015f095'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_company_name_domain_user', 'companies', type_='unique')
    op.create_unique_constraint('uix_company_name_user', 'companies', ['name', 'user_id'])
    op.drop_column('companies', 'domain')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uix_company_name_user', 'companies', type_='unique')
    op.create_unique_constraint('uix_company_name_domain_user', 'companies', ['name', 'domain', 'user_id'])
    # ### end Alembic commands ### 