"""add_delete

Revision ID: fa55872b23f2
Revises: f2344f1a15d6
Create Date: 2025-06-15 17:53:22.518264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa55872b23f2'
down_revision = 'f2344f1a15d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 